steps:
  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/pyfedi
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
  - name: mail
    image: deblan/woodpecker-email
    settings:
      dsn:
        from_secret: smtp_dsn
      from:
        address:
          from_secret: smtp_from
        name: "Woodpecker"
      recipients:
        from_secret: smtp_recipients
      recipients_only: false
      content:
        subject: "[{{ pipeline.status }}] {{ repo.full_name }} ({{ commit.branch }} - {{ commit.sha[0:8] }}"
        body: |
          {{ commit.sha }}<br>
          {{ pipeline.status }}<br>
          {{ commit.author_email }}<br>
      attachments:
        - log/*
