services:

  db:
    shm_size: 128mb
    image: postgres:16
    restart: unless-stopped
    platform: linux/amd64
    env_file:
     - ./.env.docker
    volumes:
     - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pf_network

  redis:
    image: redis:6.2
    restart: unless-stopped
    platform: linux/amd64
    env_file:
     - ./.env.docker
    networks:
      - pf_network

  celery:
    build:
      context: .
      target: builder
    container_name: piefed_celery1
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      - db
      - redis
    env_file:
     - ./.env.docker
    entrypoint: ./entrypoint_celery.sh
    volumes:
     - ./media/:/app/app/static/media/
     - ./logs/:/app/logs/
     - ./tmp/:/app/app/static/tmp/
    networks:
      - pf_network

  web:
    image: piefed_app1:2
    container_name: piefed_app1
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      - db
      - redis
    env_file:
     - ./.env.docker
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1  # Displays prints and logger.info in console
    volumes:
     - ./gunicorn.conf.py:/app/gunicorn.conf.py
     - ./media/:/app/app/static/media/
     - ./logs/:/app/logs/
     - ./tmp/:/app/app/static/tmp/
     - ./:/app:z
    ports:
      - '5050:5000'
      - '5932:5932'
    networks:
      - pf_network
    entrypoint: ./entrypoint.sh

  internal_api:
    image: piefed_app1:3
    container_name: piefed_internal_api
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.docker
    environment:
      - PYTHONUNBUFFERED=1
      - INTERNAL_API_PORT=5932
    volumes:
      - ./media/:/app/app/static/media/
      - ./logs/:/app/logs/
      - ./tmp/:/app/app/static/tmp/
      - ./:/app:z
    ports:
      - '5933:5932'
    networks:
      - pf_network
    entrypoint: python3 -m gunicorn --bind 0.0.0.0:5932 --workers 1 run_internal_api:app

  adminer:
    image: adminer
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8888:8080"
    depends_on:
      - db
    networks:
      - pf_network


networks:
  pf_network:
    name: pf_network
    external: false
