services:

  db:
    shm_size: 128mb
    image: postgres:17
    restart: unless-stopped
    user: "1000:1000"
    env_file:
     - ./.env.docker
    volumes:
     - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pf_network

  redis:
    image: redis:6.2
    restart: unless-stopped
    env_file:
     - ./.env.docker
    networks:
      - pf_network

  celery:
    build:
      context: .
      target: builder
    container_name: piefed_celery1
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
     - ./.env.docker
    entrypoint: ./entrypoint_celery.sh
    volumes:
     - ./media/:/app/app/static/media/
     - ./logs/:/app/logs/
     - ./tmp/:/app/app/static/tmp/
    networks:
      - pf_network

  web:
    build:
      context: .
      target: builder
    container_name: piefed_app1
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
     - ./.env.docker
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1  # Displays prints and logger.info in console
    volumes:
     - ./gunicorn.conf.py:/app/gunicorn.conf.py
     - ./media/:/app/app/static/media/
     - ./logs/:/app/logs/
     - ./tmp/:/app/app/static/tmp/
     - ./:/app:z
    ports:
      - '8030:5000'
    networks:
      - pf_network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8888:8080"
    depends_on:
      - db
    networks:
      - pf_network


networks:
  pf_network:
    name: pf_network
    external: false
