"""hide instances from chooser

Revision ID: 02f2fc3f19f1
Revises: 7097ec286ac8
Create Date: 2025-09-08 19:41:14.915886

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02f2fc3f19f1"
down_revision = "7097ec286ac8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_chooser", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hide", sa.Boolean(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_instance_chooser_hide"), ["hide"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_chooser", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instance_chooser_hide"))
        batch_op.drop_column("hide")

    # ### end Alembic commands ###
