"""report source

Revision ID: 04697ae91fac
Revises: 2b028a70bd7a
Create Date: 2024-03-26 22:13:16.749010

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04697ae91fac"
down_revision = "2b028a70bd7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_instance_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_report_source_instance_id", "instance", ["source_instance_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.drop_constraint("fk_report_source_instance_id", type_="foreignkey")
        batch_op.drop_column("source_instance_id")

    # ### end Alembic commands ###
