"""indexes for community stats

Revision ID: 05e8bbb98977
Revises: 1a93face316a
Create Date: 2025-07-04 20:41:08.428082

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05e8bbb98977"
down_revision = "1a93face316a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(
            "ix_post_community_created_bot",
            ["community_id", "created_at"],
            unique=False,
            postgresql_where=sa.text("from_bot = false"),
        )
        batch_op.create_index(
            "ix_post_community_posted_bot",
            ["community_id", "posted_at"],
            unique=False,
            postgresql_where=sa.text("from_bot = false"),
        )

    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.create_index(
            "ix_post_reply_community_posted_bot",
            ["community_id", "posted_at"],
            unique=False,
            postgresql_where=sa.text("from_bot = false"),
        )

    with op.batch_alter_table("post_reply_vote", schema=None) as batch_op:
        batch_op.create_index(
            "ix_post_reply_vote_created", ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_post_reply_vote_reply_created",
            ["post_reply_id", "created_at"],
            unique=False,
        )

    with op.batch_alter_table("post_vote", schema=None) as batch_op:
        batch_op.create_index("ix_post_vote_created", ["created_at"], unique=False)
        batch_op.create_index(
            "ix_post_vote_post_created", ["post_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_vote", schema=None) as batch_op:
        batch_op.drop_index("ix_post_vote_post_created")
        batch_op.drop_index("ix_post_vote_created")

    with op.batch_alter_table("post_reply_vote", schema=None) as batch_op:
        batch_op.drop_index("ix_post_reply_vote_reply_created")
        batch_op.drop_index("ix_post_reply_vote_created")

    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_post_reply_community_posted_bot",
            postgresql_where=sa.text("from_bot = false"),
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_post_community_posted_bot", postgresql_where=sa.text("from_bot = false")
        )
        batch_op.drop_index(
            "ix_post_community_created_bot",
            postgresql_where=sa.text("from_bot = false"),
        )

    # ### end Alembic commands ###
