"""adding joined_via_feed to community_join_request

Revision ID: 07089cee1afb
Revises: 4b1b69e964f0
Create Date: 2025-03-07 10:00:41.494377

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07089cee1afb"
down_revision = "4b1b69e964f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community_join_request", schema=None) as batch_op:
        batch_op.add_column(sa.Column("joined_via_feed", sa.Boolean(), nullable=True))

    with op.batch_alter_table("community_join_request", schema=None) as batch_op:
        batch_op.execute('UPDATE "community_join_request" SET joined_via_feed = false')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community_join_request", schema=None) as batch_op:
        batch_op.drop_column("joined_via_feed")

    # ### end Alembic commands ###
