"""instance chooser migration

Revision ID: 086ebbe4f31b
Revises: 9feef6cf2e9f
Create Date: 2025-08-15 15:15:40.457238

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "086ebbe4f31b"
down_revision = "9feef6cf2e9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance_chooser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=True),
        sa.Column("language_id", sa.Integer(), nullable=True),
        sa.Column("nsfw", sa.Boolean(), nullable=True),
        sa.Column("newbie_friendly", sa.Boolean(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("instance_chooser", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_instance_chooser_domain"), ["domain"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_chooser_language_id"), ["language_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_chooser_newbie_friendly"),
            ["newbie_friendly"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_instance_chooser_nsfw"), ["nsfw"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_chooser", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instance_chooser_nsfw"))
        batch_op.drop_index(batch_op.f("ix_instance_chooser_newbie_friendly"))
        batch_op.drop_index(batch_op.f("ix_instance_chooser_language_id"))
        batch_op.drop_index(batch_op.f("ix_instance_chooser_domain"))

    op.drop_table("instance_chooser")
    # ### end Alembic commands ###
