"""suppress cross posts

Revision ID: 089767dd3afc
Revises: ba02c97c1722
Create Date: 2025-07-08 19:57:58.270549

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "089767dd3afc"
down_revision = "ba02c97c1722"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("suppress_crossposts", sa.Boolean(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_suppress_crossposts"),
            ["suppress_crossposts"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_suppress_crossposts"))
        batch_op.drop_column("suppress_crossposts")

    # ### end Alembic commands ###
