"""cross posts

Revision ID: 08b3f718df5d
Revises: 04697ae91fac
Create Date: 2024-03-31 02:10:19.726154

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "08b3f718df5d"
down_revision = "04697ae91fac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cross_posts", postgresql.ARRAY(sa.Integer()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("cross_posts")

    # ### end Alembic commands ###
