"""read_posts composite index

Revision ID: 0c0999b40c62
Revises: 5309218d9d9e
Create Date: 2025-08-02 19:23:17.112953

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c0999b40c62"
down_revision = "5309218d9d9e"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        DELETE FROM "read_posts"
        WHERE ctid IN (
            SELECT ctid FROM (
                SELECT ctid,
                       ROW_NUMBER() OVER (
                           PARTITION BY user_id, read_post_id
                           ORDER BY interacted_at DESC NULLS LAST
                       ) AS rn
                FROM read_posts
            ) sub
            WHERE sub.rn > 1
        );
    """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("read_posts", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "read_post_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.create_index(
            "ix_read_posts_user_post", ["user_id", "read_post_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("read_posts", schema=None) as batch_op:
        batch_op.drop_index("ix_read_posts_user_post")
        batch_op.alter_column("read_post_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
