"""Increase password hash field length

Revision ID: 0e4d615995a3
Revises: 3b9ccd7cdb57
Create Date: 2025-07-23 17:47:33.430384

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e4d615995a3"
down_revision = "3b9ccd7cdb57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=150),
            type_=sa.String(length=165),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=165),
            type_=sa.VARCHAR(length=150),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
