"""add uuid to feedjoinrequest

Revision ID: 0e7b7b308de4
Revises: 7db344090ec5
Create Date: 2025-06-16 16:06:03.975629

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e7b7b308de4"
down_revision = "7db344090ec5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_join_request", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_feed_join_request_uuid"), ["uuid"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_join_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_join_request_uuid"))
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
