"""private groups

Revision ID: 0f79379c3e8a
Revises: 6814385881d3
Create Date: 2026-01-26 13:51:55.887875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f79379c3e8a'
down_revision = '6814385881d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=25), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_invitation_token'), ['token'], unique=False)

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted', sa.Boolean(), server_default=sa.sql.false(), nullable=True))
        batch_op.add_column(sa.Column('invitations', sa.Integer(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('invitations')
        batch_op.drop_column('encrypted')

    with op.batch_alter_table('community_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_invitation_token'))

    op.drop_table('community_invitation')
    # ### end Alembic commands ###
