"""domain post warning

Revision ID: 1189f921aca6
Revises: f2fa25ab5e52
Create Date: 2024-12-13 19:17:15.319197

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1189f921aca6"
down_revision = "f2fa25ab5e52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("domain", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("post_warning", sa.String(length=512), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("domain", schema=None) as batch_op:
        batch_op.drop_column("post_warning")

    # ### end Alembic commands ###
