"""ap_featured_url

Revision ID: 12d60b9d5417
Revises: 81175e11c083
Create Date: 2024-03-19 07:05:04.588051

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12d60b9d5417"
down_revision = "81175e11c083"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ap_featured_url", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("ap_featured_url")

    # ### end Alembic commands ###
