"""bot challenge

Revision ID: 1521210bd33a
Revises: c4f4625a6922
Create Date: 2026-06-25 16:05:26.094994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1521210bd33a'
down_revision = 'c4f4625a6922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('is_a_bot', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_challenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_challenge_sent_by'), ['sent_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_challenge_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_challenge_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_challenge_uuid'))
        batch_op.drop_index(batch_op.f('ix_bot_challenge_user_id'))
        batch_op.drop_index(batch_op.f('ix_bot_challenge_sent_by'))

    op.drop_table('bot_challenge')
    # ### end Alembic commands ###
