"""Added a column to remember if a user has completed the onboarding

Revision ID: 153acfa3f34b
Revises: a84df9b8223c
Create Date: 2026-03-17 15:54:53.806996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153acfa3f34b'
down_revision = 'a84df9b8223c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_onboarding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('finished_onboarding')

    # ### end Alembic commands ###
