"""scheduled post status

Revision ID: 181aee7fa08d
Revises: 42c8f19220f2
Create Date: 2025-05-04 03:43:46.426436

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "181aee7fa08d"
down_revision = "42c8f19220f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_post_status"), ["status"], unique=False)

    conn = op.get_bind()
    conn.execute(text('UPDATE "post" SET status = 1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_status"))
        batch_op.drop_column("status")

    # ### end Alembic commands ###
