"""community stats

Revision ID: 1a93face316a
Revises: f392f91ea9be
Create Date: 2025-07-03 20:07:34.572832

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a93face316a"
down_revision = "f392f91ea9be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active_daily", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("active_weekly", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("active_monthly", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("active_6monthly", sa.Integer(), nullable=True))

    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tos_url", sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("tos_url")

    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("active_6monthly")
        batch_op.drop_column("active_monthly")
        batch_op.drop_column("active_weekly")
        batch_op.drop_column("active_daily")

    # ### end Alembic commands ###
