"""topic countries

Revision ID: 1adb45ab3971
Revises: b7d47f22842f
Create Date: 2026-05-30 12:43:10.189786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1adb45ab3971'
down_revision = 'b7d47f22842f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('countries', postgresql.ARRAY(sa.String(length=15)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('countries')

    # ### end Alembic commands ###
