"""blocked images

Revision ID: 1afe12b081f6
Revises: 3508ca8ba54d
Create Date: 2025-05-12 19:45:43.892458

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1afe12b081f6"
down_revision = "3508ca8ba54d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("hash", postgresql.BIT(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blocked_image", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_blocked_image_file_name"), ["file_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_blocked_image_hash"), ["hash"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blocked_image", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blocked_image_hash"))
        batch_op.drop_index(batch_op.f("ix_blocked_image_file_name"))

    op.drop_table("blocked_image")
    # ### end Alembic commands ###
