"""community default post type

Revision ID: 1b0b1a3f63b1
Revises: 25ac2012570d
Create Date: 2025-10-17 14:29:43.936626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0b1a3f63b1'
down_revision = '25ac2012570d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_post_type', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('default_post_type')

    # ### end Alembic commands ###
