"""private instance

Revision ID: 1b228182c8be
Revises: 181aee7fa08d
Create Date: 2025-05-09 12:11:49.123052

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "1b228182c8be"
down_revision = "181aee7fa08d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("private_instance", sa.Boolean(), nullable=True))

    conn = op.get_bind()
    conn.execute(text('UPDATE "site" SET private_instance = false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("private_instance")

    # ### end Alembic commands ###
