"""Add TOTP fields to user

Revision ID: 20250801193400
Revises: 20250801192840
Create Date: 2025-08-01 19:34:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250801193400'
down_revision = '20250801192840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(64), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('totp_recovery_codes', sa.Text(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE \"user\" SET totp_enabled = false WHERE totp_enabled IS NULL")
    
    # Make totp_enabled not nullable after setting defaults
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('totp_enabled',
                              existing_type=sa.Boolean(),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_recovery_codes')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')
    # ### end Alembic commands ###