"""Add user suspended column

Revision ID: 20250801192840
Revises: 8272566919f0
Create Date: 2025-08-01 19:28:40.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250801192840'
down_revision = '8272566919f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_suspended'), ['suspended'], unique=False)

    # Set default value for existing rows
    op.execute("UPDATE \"user\" SET suspended = false WHERE suspended IS NULL")
    
    # Make column not nullable after setting defaults
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('suspended',
                              existing_type=sa.Boolean(),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_suspended'))
        batch_op.drop_column('suspended')
    # ### end Alembic commands ###