"""tag formatting

Revision ID: 20ee24728510
Revises: 9ad372b72d7c
Create Date: 2024-05-11 13:42:31.772863

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20ee24728510"
down_revision = "9ad372b72d7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("display_as", sa.String(length=256), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_tag_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tag_name"))
        batch_op.drop_column("display_as")

    # ### end Alembic commands ###
