"""allowlist mode

Revision ID: 21ed7db16be0
Revises: e2e129221248
Create Date: 2026-05-27 20:25:05.627068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ed7db16be0'
down_revision = 'e2e129221248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowlist_mode', sa.Integer(), nullable=True, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('allowlist_mode')

    # ### end Alembic commands ###
