"""instance liability

Revision ID: 230b284eaa7f
Revises: d4e8677025cd
Create Date: 2026-10-03 10:53:34.747609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230b284eaa7f'
down_revision = 'd4e8677025cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defederated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('defederated_reason', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('liability', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instance_defederated'), ['defederated'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_liability'), ['liability'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_liability'))
        batch_op.drop_index(batch_op.f('ix_instance_defederated'))
        batch_op.drop_column('liability')
        batch_op.drop_column('defederated_reason')
        batch_op.drop_column('defederated')

    # ### end Alembic commands ###
