"""remove slug index

Revision ID: 2411d5c6539e
Revises: f9a75d6851c9
Create Date: 2025-10-18 09:24:47.684202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2411d5c6539e'
down_revision = 'f9a75d6851c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_slug', ['slug'], unique=False)

    # ### end Alembic commands ###
