"""Add code style option

Revision ID: 25ac2012570d
Revises: 8bfaa7ebb160
Create Date: 2025-10-14 01:52:25.551731

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25ac2012570d"
down_revision = "8bfaa7ebb160"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("code_style", sa.String(length=25), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("code_style")

    # ### end Alembic commands ###
