"""remove file hash

Revision ID: 27fd5a56a831
Revises: 1b228182c8be
Create Date: 2025-05-12 19:34:55.430685

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27fd5a56a831"
down_revision = "1b228182c8be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index("ix_file_hash")
        batch_op.drop_column("hash")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True)
        )
        batch_op.create_index("ix_file_hash", ["hash"], unique=False)

    # ### end Alembic commands ###
