"""blocked phrases

Revision ID: 2b028a70bd7a
Revises: 12d60b9d5417
Create Date: 2024-03-22 11:50:15.405786

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b028a70bd7a"
down_revision = "12d60b9d5417"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blocked_phrases", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("blocked_phrases")

    # ### end Alembic commands ###
