"""notification title length

Revision ID: 2c3a0e0c5b57
Revises: c061eec8c280
Create Date: 2025-04-19 17:32:27.158645

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c3a0e0c5b57"
down_revision = "c061eec8c280"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=150),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=150),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
