"""gen ai

Revision ID: 2dab0fc0b964
Revises: 7b6833b97181
Create Date: 2025-11-30 15:04:05.008584

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2dab0fc0b964"
down_revision = "7b6833b97181"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_generated", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("ignore_remote_gen_ai", sa.Boolean(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_community_ai_generated"), ["ai_generated"], unique=False
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ai_generated",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_post_ai_generated"), ["ai_generated"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hide_gen_ai", sa.Integer(), server_default=sa.text("2"), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("hide_gen_ai")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_ai_generated"))
        batch_op.drop_column("ai_generated")

    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_community_ai_generated"))
        batch_op.drop_column("ignore_remote_gen_ai")
        batch_op.drop_column("ai_generated")

    # ### end Alembic commands ###
