"""enable or disable honeypot

Revision ID: 2e36f0fc3c22
Revises: 4dfc7513c4ae
Create Date: 2026-01-07 12:32:22.126791

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e36f0fc3c22"
down_revision = "4dfc7513c4ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "honeypot", sa.Boolean(), server_default=sa.sql.true(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("honeypot")

    # ### end Alembic commands ###
