"""google oauth

Revision ID: 2ea29b01e5c6
Revises: b6169d302035
Create Date: 2025-04-22 20:27:12.716678

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ea29b01e5c6"
down_revision = "b6169d302035"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_oauth_id", sa.String(length=64), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_google_oauth_id"), ["google_oauth_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_google_oauth_id"))
        batch_op.drop_column("google_oauth_id")

    # ### end Alembic commands ###
