"""instance popular

Revision ID: 336345ec53d0
Revises: 153acfa3f34b
Create Date: 2026-03-18 15:46:30.508677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336345ec53d0'
down_revision = '153acfa3f34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popular', sa.Boolean(), server_default=sa.sql.true(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('popular')

    # ### end Alembic commands ###
