"""indexes on user and post

Revision ID: 33f803f63f74
Revises: 77d0b8e3135e
Create Date: 2026-02-21 14:16:38.154294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f803f63f74'
down_revision = '77d0b8e3135e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('idx_post_reports_gt_0', ['id'], unique=False, postgresql_where=sa.text('reports > 0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_user_name_lower', [sa.literal_column('lower(user_name)')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_user_name_lower')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('idx_post_reports_gt_0', postgresql_where=sa.text('reports > 0'))

    # ### end Alembic commands ###
