"""add file hash as bit

Revision ID: 3508ca8ba54d
Revises: 27fd5a56a831
Create Date: 2025-05-12 19:35:31.032372

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3508ca8ba54d"
down_revision = "27fd5a56a831"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("hash", postgresql.BIT(length=256), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_file_hash"), ["hash"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_hash"))
        batch_op.drop_column("hash")

    # ### end Alembic commands ###
