"""Admin notes on instances

Revision ID: 398ca067c08f
Revises: a5f63c1add4d
Create Date: 2026-01-29 05:39:54.704730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398ca067c08f'
down_revision = 'a5f63c1add4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))

    with op.batch_alter_table('post_reply_vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_reply_vote_post_reply_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post_reply', ['post_reply_id'], ['id'])

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_vote_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_vote_post_id_fkey'), 'post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_reply_vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_reply_vote_post_reply_id_fkey'), 'post_reply', ['post_reply_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('admin_note')

    # ### end Alembic commands ###
