"""new instances index

Revision ID: 41d7b55a5fa8
Revises: 33f803f63f74
Create Date: 2026-02-23 10:09:11.536001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d7b55a5fa8'
down_revision = '33f803f63f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.create_index('ix_instance_created_at_active', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('gone_forever = false AND dormant = false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_index('ix_instance_created_at_active', postgresql_where=sa.text('gone_forever = false AND dormant = false'))

    # ### end Alembic commands ###
