"""flair

Revision ID: 42c8f19220f2
Revises: 636ceb33040a
Create Date: 2025-05-03 12:31:35.990952

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42c8f19220f2"
down_revision = "636ceb33040a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_flair",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=True),
        sa.Column("flair", sa.String(length=50), nullable=True),
        sa.Column("text_color", sa.String(length=50), nullable=True),
        sa.Column("background_color", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("community_flair", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_community_flair_community_id"),
            ["community_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_community_flair_flair"), ["flair"], unique=False
        )

    op.create_table(
        "user_flair",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("community_id", sa.Integer(), nullable=True),
        sa.Column("flair", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_flair", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_flair_community_id"), ["community_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_flair_flair"), ["flair"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_flair_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "post_flair",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("flair_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flair_id"],
            ["community_flair.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "flair_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_flair")
    with op.batch_alter_table("user_flair", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_flair_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_flair_flair"))
        batch_op.drop_index(batch_op.f("ix_user_flair_community_id"))

    op.drop_table("user_flair")
    with op.batch_alter_table("community_flair", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_community_flair_flair"))
        batch_op.drop_index(batch_op.f("ix_community_flair_community_id"))

    op.drop_table("community_flair")
    # ### end Alembic commands ###
