"""mini cms

Revision ID: 436ebe26b0fe
Revises: ba02110b0962
Create Date: 2025-06-10 14:55:44.318806

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "436ebe26b0fe"
down_revision = "ba02110b0962"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cms_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("last_edited_by", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cms_page", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cms_page_url"), ["url"], unique=False)

    # ### end Alembic commands ###
    conn = op.get_bind()
    exists = conn.execute(
        text('SELECT id FROM "role" WHERE name = :name'), {"name": "Admin"}
    ).scalar()
    if exists:
        conn.execute(
            text(
                "INSERT INTO \"role_permission\" (role_id, permission) VALUES (4, 'edit cms pages')"
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cms_page", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cms_page_url"))

    op.drop_table("cms_page")
    # ### end Alembic commands ###
