"""Add total_ratings column to Community

Revision ID: 447b36276635
Revises: 801a68148235
Create Date: 2025-11-19 04:45:14.345780

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "447b36276635"
down_revision = "801a68148235"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_ratings", sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    conn = op.get_bind()
    rated_comms = conn.execute(
        text('SELECT DISTINCT ON (community_id) community_id FROM "rating"')
    ).all()
    if rated_comms:
        for comm in rated_comms:
            comm_id = comm[0]
            num_ratings = conn.execute(
                text(
                    'SELECT COUNT(id) FROM "rating" WHERE community_id = :community_id AND rating is not null'
                ),
                {"community_id": comm_id},
            ).first()
            conn.execute(
                text(
                    'UPDATE "community" SET total_ratings = :num_ratings WHERE id = :community_id'
                ),
                {"num_ratings": num_ratings[0], "community_id": comm_id},
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("total_ratings")

    # ### end Alembic commands ###
