"""community rss

Revision ID: 46b2b16d498b
Revises: 8ed167b06fd7
Create Date: 2026-08-08 15:48:50.294249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b2b16d498b'
down_revision = '8ed167b06fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('check_frequency', sa.Integer(), nullable=True),
    sa.Column('flair_id', sa.Integer(), nullable=True),
    sa.Column('next_check', sa.DateTime(), nullable=False),
    sa.Column('etag', sa.String(length=512), nullable=True),
    sa.Column('last_modified', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.DateTime(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['flair_id'], ['community_flair.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rss_feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rss_feed_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rss_feed_next_check'), ['next_check'], unique=False)

    op.create_table('rss_feed_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=2048), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feed.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'guid')
    )
    with op.batch_alter_table('rss_feed_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rss_feed_item_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rss_feed_item_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_feed_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rss_feed_item_post_id'))
        batch_op.drop_index(batch_op.f('ix_rss_feed_item_feed_id'))

    op.drop_table('rss_feed_item')
    with op.batch_alter_table('rss_feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rss_feed_next_check'))
        batch_op.drop_index(batch_op.f('ix_rss_feed_community_id'))

    op.drop_table('rss_feed')
    # ### end Alembic commands ###
