"""long instance about field

Revision ID: 46c170499e71
Revises: 7aee4cb7db24
Create Date: 2024-04-22 18:28:51.826149

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46c170499e71"
down_revision = "7aee4cb7db24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("about", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("about")

    # ### end Alembic commands ###
