"""distinguished comments

Revision ID: 48fbaff6e3a5
Revises: 5c379d2b2d48
Create Date: 2025-05-23 09:18:11.226378

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48fbaff6e3a5"
down_revision = "5c379d2b2d48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.add_column(sa.Column("distinguished", sa.Boolean(), nullable=True))
        batch_op.drop_index("ix_post_reply_nsfl")
        batch_op.drop_column("nsfl")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("nsfl", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )
        batch_op.create_index("ix_post_reply_nsfl", ["nsfl"], unique=False)
        batch_op.drop_column("distinguished")

    # ### end Alembic commands ###
