"""adding user feed auto follow and leave

Revision ID: 4b1b69e964f0
Revises: 1cc1c8ff75fe
Create Date: 2025-03-06 15:55:46.833409

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b1b69e964f0"
down_revision = "1cc1c8ff75fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("feed_auto_follow", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("feed_auto_leave", sa.Boolean(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.execute(
            'UPDATE "user" SET feed_auto_follow = true WHERE instance_id = 1'
        )
        batch_op.execute(
            'UPDATE "user" SET feed_auto_leave = true WHERE instance_id = 1'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("feed_auto_leave")
        batch_op.drop_column("feed_auto_follow")

    # ### end Alembic commands ###
