"""remove vote weight

Revision ID: 4dfc7513c4ae
Revises: b1dd589ac3f9
Create Date: 2026-01-03 15:36:48.403355

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4dfc7513c4ae"
down_revision = "b1dd589ac3f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.alter_column(
            "first_federated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.drop_column("vote_weight")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "vote_weight",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.alter_column(
            "first_federated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    # ### end Alembic commands ###
