"""hidden posts

Revision ID: 51d55a05bfca
Revises: fbd19ecc0c3a
Create Date: 2025-12-21 15:19:51.876748

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51d55a05bfca"
down_revision = "fbd19ecc0c3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hidden_posts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hidden_post_id", sa.Integer(), nullable=False),
        sa.Column("interacted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hidden_post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "hidden_post_id"),
    )
    with op.batch_alter_table("hidden_posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hidden_posts_interacted_at"), ["interacted_at"], unique=False
        )
        batch_op.create_index(
            "ix_hidden_posts_user_post", ["user_id", "hidden_post_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hidden_posts", schema=None) as batch_op:
        batch_op.drop_index("ix_hidden_posts_user_post")
        batch_op.drop_index(batch_op.f("ix_hidden_posts_interacted_at"))

    op.drop_table("hidden_posts")
    # ### end Alembic commands ###
