"""additional css

Revision ID: 52380f7885d1
Revises: 750ae072ec51
Create Date: 2025-04-04 11:39:06.871342

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52380f7885d1"
down_revision = "750ae072ec51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("additional_css", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("additional_css")

    # ### end Alembic commands ###
