"""float post ranking

Revision ID: 544946659eb7
Revises: c831b9c7eee9
Create Date: 2026-07-07 19:14:01.527883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544946659eb7'
down_revision = 'c831b9c7eee9'
branch_labels = None
depends_on = None


def upgrade():
    # PostgreSQL refuses to change a column's type while a view or rule depends
    # on it:
    #     psycopg2.errors.FeatureNotSupported: cannot alter type of a column
    #     used by a view or rule
    #     DETAIL: rule _RETURN on materialized view post_view depends on
    #     column "ranking"
    #
    # This fork created the post_view materialized view in e44dfb9a157f and
    # dropped it again in 8457362452d9, when the post list moved to an
    # indexes-based approach. Databases that were stamped, or restored from a
    # dump predating that drop, still carry the view, so upstream's bare
    # ALTER COLUMN aborts the whole upgrade for them. Upstream does not hit this
    # because their databases have no leftover view.
    #
    # The view is derived data and nothing queries it -- every `post_view`
    # reference in app/ is the Python serializer of the same name -- so dropping
    # it is safe rather than destructive. IF EXISTS makes this a no-op on
    # databases that never had it, and CASCADE clears its dependent indexes.
    op.execute("DROP MATERIALIZED VIEW IF EXISTS post_view CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('ranking_scaled',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('ranking_scaled',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ranking',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
