"""font

Revision ID: 55ea8c349fd3
Revises: 1afe12b081f6
Create Date: 2025-05-15 19:30:10.362886

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55ea8c349fd3"
down_revision = "1afe12b081f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("font", sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("font")

    # ### end Alembic commands ###
