"""read_posts primary

Revision ID: 569d6f8c32bd
Revises: 0c0999b40c62
Create Date: 2025-08-02 19:28:03.169006

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "569d6f8c32bd"
down_revision = "0c0999b40c62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("read_posts", schema=None) as batch_op:
        batch_op.drop_index("ix_read_posts_read_post_id")
        batch_op.drop_index("ix_read_posts_user_id")

    # ### end Alembic commands ###

    # Add composite primary key
    op.create_primary_key(
        constraint_name="pk_read_posts",
        table_name="read_posts",
        columns=["user_id", "read_post_id"],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("read_posts", schema=None) as batch_op:
        batch_op.create_index("ix_read_posts_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "ix_read_posts_read_post_id", ["read_post_id"], unique=False
        )

    # ### end Alembic commands ###
