"""user reg warning

Revision ID: 59792d8577df
Revises: 48fbaff6e3a5
Create Date: 2025-05-23 19:59:10.148528

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59792d8577df"
down_revision = "48fbaff6e3a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_registration", schema=None) as batch_op:
        batch_op.add_column(sa.Column("warning", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_registration", schema=None) as batch_op:
        batch_op.drop_column("warning")

    # ### end Alembic commands ###
