"""filter options

Revision ID: 5bee0ac7d99f
Revises: 363f2f07ff30
Create Date: 2024-06-28 13:48:47.692409

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5bee0ac7d99f"
down_revision = "363f2f07ff30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.execute('UPDATE "user" SET show_nsfw = NOT show_nsfw')
        batch_op.alter_column("show_nsfw", new_column_name="hide_nsfw")
        batch_op.alter_column(
            "hide_nsfw",
            existing_type=sa.BOOLEAN(),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using="hide_nsfw::integer",
        )
        batch_op.execute('UPDATE "user" SET show_nsfl = NOT show_nsfl')
        batch_op.alter_column("show_nsfl", new_column_name="hide_nsfl")
        batch_op.alter_column(
            "hide_nsfl",
            existing_type=sa.BOOLEAN(),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using="hide_nsfl::integer",
        )
        batch_op.alter_column(
            "ignore_bots",
            existing_type=sa.BOOLEAN(),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using="ignore_bots::integer",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "ignore_bots",
            existing_type=sa.Integer(),
            type_=sa.BOOLEAN(),
            existing_nullable=True,
            postgresql_using="ignore_bots::boolean",
        )
        batch_op.execute(
            'UPDATE "user" SET hide_nsfl = CASE WHEN hide_nsfl = 1 THEN 0 ELSE 1 END'
        )
        batch_op.alter_column("hide_nsfl", new_column_name="show_nsfl")
        batch_op.alter_column(
            "show_nsfl",
            existing_type=sa.Integer(),
            type_=sa.BOOLEAN(),
            existing_nullable=True,
            postgresql_using="show_nsfl::boolean",
        )
        batch_op.execute(
            'UPDATE "user" SET hide_nsfw = CASE WHEN hide_nsfw = 1 THEN 0 ELSE 1 END'
        )
        batch_op.alter_column("hide_nsfw", new_column_name="show_nsfw")
        batch_op.alter_column(
            "show_nsfw",
            existing_type=sa.Integer(),
            type_=sa.BOOLEAN(),
            existing_nullable=True,
            postgresql_using="show_nsfw::boolean",
        )

    # ### end Alembic commands ###
