"""detect ip country

Revision ID: 5bf49b8b7b79
Revises: b97584a7a10b
Create Date: 2024-08-01 15:59:39.914142

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5bf49b8b7b79"
down_revision = "b97584a7a10b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ip_address_country", sa.String(length=50), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("ip_address_country")

    # ### end Alembic commands ###
