"""private vote tweak

Revision ID: 5c379d2b2d48
Revises: 6bfd83e619dd
Create Date: 2025-05-22 22:21:22.936571

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "5c379d2b2d48"
down_revision = "6bfd83e619dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("vote_privately", sa.Boolean(), nullable=True))
    conn = op.get_bind()
    conn.execute(text('UPDATE "user" SET vote_privately = false'))
    conn.execute(
        text(
            "UPDATE \"user\" SET vote_privately = true WHERE alt_user_name is not null AND alt_user_name != ''"
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("vote_privately")

    # ### end Alembic commands ###
