"""favorite communities

Revision ID: 5eb2bf95ed8b
Revises: 9208f044a1db
Create Date: 2026-06-22 10:01:08.154079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb2bf95ed8b'
down_revision = '9208f044a1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'community_id')
    )
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('un_moderated', sa.Boolean(), nullable=True, server_default=sa.sql.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('un_moderated')

    op.drop_table('community_favorite')
    # ### end Alembic commands ###
