"""scheduled posts on post

Revision ID: 636ceb33040a
Revises: 809371c5b2ee
Create Date: 2025-05-03 09:16:15.909369

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "636ceb33040a"
down_revision = "809371c5b2ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scheduled_for", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("repeat", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("stop_repeating", sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_post_scheduled_for"), ["scheduled_for"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_post_stop_repeating"), ["stop_repeating"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_stop_repeating"))
        batch_op.drop_index(batch_op.f("ix_post_scheduled_for"))
        batch_op.drop_column("stop_repeating")
        batch_op.drop_column("repeat")
        batch_op.drop_column("scheduled_for")

    # ### end Alembic commands ###
