"""adding feeds db changes

Revision ID: 63c587b2c6bc
Revises: 7f163d621f13
Create Date: 2025-02-15 19:08:19.493530

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "63c587b2c6bc"
down_revision = "7f163d621f13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("machine_name", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("nsfw", sa.Boolean(), nullable=True),
        sa.Column("nsfl", sa.Boolean(), nullable=True),
        sa.Column("public_key", sa.Text(), nullable=True),
        sa.Column("private_key", sa.Text(), nullable=True),
        sa.Column("subscriptions_count", sa.Integer(), nullable=True),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("icon_id", sa.Integer(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("num_communities", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("last_edit", sa.DateTime(), nullable=True),
        sa.Column("parent_feed_id", sa.Integer(), nullable=True),
        sa.Column("is_instance_feed", sa.Boolean(), nullable=True),
        sa.Column("ap_id", sa.String(length=255), nullable=True),
        sa.Column("ap_profile_id", sa.String(length=255), nullable=True),
        sa.Column("ap_public_url", sa.String(length=255), nullable=True),
        sa.Column("ap_followers_url", sa.String(length=255), nullable=True),
        sa.Column("ap_following_url", sa.String(length=255), nullable=True),
        sa.Column("ap_domain", sa.String(length=255), nullable=True),
        sa.Column("ap_preferred_username", sa.String(length=255), nullable=True),
        sa.Column("ap_discoverable", sa.Boolean(), nullable=True),
        sa.Column("ap_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("ap_deleted_at", sa.DateTime(), nullable=True),
        sa.Column("ap_inbox_url", sa.String(length=255), nullable=True),
        sa.Column("ap_outbox_url", sa.String(length=255), nullable=True),
        sa.Column("ap_moderators_url", sa.String(length=255), nullable=True),
        sa.Column("banned", sa.Boolean(), nullable=True),
        sa.Column("searchable", sa.Boolean(), nullable=True),
        sa.Column("show_posts_in_children", sa.Boolean(), nullable=True),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["icon_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feed_ap_id"), ["ap_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_feed_ap_profile_id"), ["ap_profile_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_feed_instance_id"), ["instance_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_feed_machine_name"), ["machine_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_feed_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_feed_parent_feed_id"), ["parent_feed_id"], unique=False
        )

    op.create_table(
        "feed_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("community_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feed_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feed_item_community_id"), ["community_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_feed_item_feed_id"), ["feed_id"], unique=False
        )

    op.create_table(
        "feed_join_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feed_join_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feed_join_request_feed_id"), ["feed_id"], unique=False
        )

    op.create_table(
        "feed_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("is_owner", sa.Boolean(), nullable=True),
        sa.Column("notify_new_communities", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feed_member", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feed_member_feed_id"), ["feed_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_feed_member_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_member_user_id"))
        batch_op.drop_index(batch_op.f("ix_feed_member_feed_id"))

    op.drop_table("feed_member")
    with op.batch_alter_table("feed_join_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_join_request_feed_id"))

    op.drop_table("feed_join_request")
    with op.batch_alter_table("feed_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_item_feed_id"))
        batch_op.drop_index(batch_op.f("ix_feed_item_community_id"))

    op.drop_table("feed_item")
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_parent_feed_id"))
        batch_op.drop_index(batch_op.f("ix_feed_name"))
        batch_op.drop_index(batch_op.f("ix_feed_machine_name"))
        batch_op.drop_index(batch_op.f("ix_feed_instance_id"))
        batch_op.drop_index(batch_op.f("ix_feed_ap_profile_id"))
        batch_op.drop_index(batch_op.f("ix_feed_ap_id"))

    op.drop_table("feed")
    # ### end Alembic commands ###
