"""cross-posted reply count

Revision ID: 6814385881d3
Revises: dd04745585ac
Create Date: 2026-01-25 10:17:13.197732

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6814385881d3"
down_revision = "dd04745585ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reply_count_cross_posted", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("reply_count_cross_posted")

    # ### end Alembic commands ###
