"""record remote edit time

Revision ID: 750ae072ec51
Revises: bb2b422094cc
Create Date: 2025-04-03 17:14:35.076825

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "750ae072ec51"
down_revision = "bb2b422094cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ap_updated", sa.DateTime(), nullable=True))

    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ap_updated", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_column("ap_updated")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("ap_updated")

    # ### end Alembic commands ###
