"""remove community rate

Revision ID: 7524920417ef
Revises: 2e36f0fc3c22
Create Date: 2026-01-10 14:47:39.317233

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7524920417ef"
down_revision = "2e36f0fc3c22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rating", schema=None) as batch_op:
        batch_op.drop_index("ix_rating_community_id")
        batch_op.drop_index("ix_rating_created_at")
        batch_op.drop_index("ix_rating_user_id")

    op.drop_table("rating")
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("average_rating")
        batch_op.drop_column("total_ratings")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("total_ratings", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "average_rating",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )

    op.create_table(
        "rating",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["community_id"], ["community.id"], name="rating_community_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="rating_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="rating_pkey"),
    )
    with op.batch_alter_table("rating", schema=None) as batch_op:
        batch_op.create_index("ix_rating_user_id", ["user_id"], unique=False)
        batch_op.create_index("ix_rating_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_rating_community_id", ["community_id"], unique=False)

    # ### end Alembic commands ###
