"""scheduled posts

Revision ID: 755c3ffc142b
Revises: e5b27b52ad78
Create Date: 2025-04-29 21:22:32.755517

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "755c3ffc142b"
down_revision = "e5b27b52ad78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("community_id", sa.Integer(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("domain_id", sa.Integer(), nullable=True),
        sa.Column("licence_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("microblog", sa.Boolean(), nullable=True),
        sa.Column("nsfw", sa.Boolean(), nullable=True),
        sa.Column("nsfl", sa.Boolean(), nullable=True),
        sa.Column("sticky", sa.Boolean(), nullable=True),
        sa.Column("indexable", sa.Boolean(), nullable=True),
        sa.Column("from_bot", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("language_id", sa.Integer(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(), nullable=True),
        sa.Column("repeat", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
        ),
        sa.ForeignKeyConstraint(
            ["licence_id"],
            ["licence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduled_post", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_community_id"), ["community_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_domain_id"), ["domain_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_from_bot"), ["from_bot"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_image_id"), ["image_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_language_id"), ["language_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_licence_id"), ["licence_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_nsfl"), ["nsfl"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_nsfw"), ["nsfw"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_scheduled_for"),
            ["scheduled_for"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_sticky"), ["sticky"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_post_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scheduled_post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_post_user_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_sticky"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_scheduled_for"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_nsfw"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_nsfl"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_licence_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_language_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_image_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_from_bot"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_domain_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_created_at"))
        batch_op.drop_index(batch_op.f("ix_scheduled_post_community_id"))

    op.drop_table("scheduled_post")
    # ### end Alembic commands ###
