"""community hashtag

Revision ID: 77af2bc5bc3b
Revises: 366426cd4111
Create Date: 2026-10-06 10:20:09.230921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77af2bc5bc3b'
down_revision = '366426cd4111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_hashtag', sa.String(length=75), server_default=sa.text("''"), nullable=True))

    with op.batch_alter_table('community_flair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_hashtag', sa.String(length=75), server_default=sa.text("''"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_flair', schema=None) as batch_op:
        batch_op.drop_column('default_hashtag')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('default_hashtag')

    # ### end Alembic commands ###
