"""post archive

Revision ID: 7928b07490fe
Revises: c579fa943828
Create Date: 2025-07-28 13:47:40.434171

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7928b07490fe"
down_revision = "c579fa943828"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("archived", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("archived")

    # ### end Alembic commands ###
