"""qna communities

Revision ID: 7b6833b97181
Revises: 447b36276635
Create Date: 2025-11-28 12:02:25.176699

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b6833b97181"
down_revision = "447b36276635"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "question_answer",
                sa.Boolean(),
                server_default=sa.sql.false(),
                nullable=True,
            )
        )

    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "answer", sa.Boolean(), server_default=sa.sql.false(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_column("answer")

    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("question_answer")

    # ### end Alembic commands ###
