"""site primary language

Revision ID: 7db344090ec5
Revises: 8afe3ee4fad0
Create Date: 2025-06-14 14:48:05.173917

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7db344090ec5"
down_revision = "8afe3ee4fad0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("language_id")

    # ### end Alembic commands ###
