"""PM control

Revision ID: 7ec262d6a3de
Revises: f668bbb1160f
Create Date: 2025-04-13 19:16:07.871809

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "7ec262d6a3de"
down_revision = "f668bbb1160f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("send_queue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_send_queue_actor"), ["actor"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("accept_private_messages", sa.Integer(), nullable=True)
        )

    conn = op.get_bind()
    conn.execute(
        text('UPDATE "user" SET accept_private_messages = 1 WHERE ap_id is null')
    )
    conn.execute(
        text('UPDATE "user" SET accept_private_messages = 3 WHERE ap_id is not null')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("accept_private_messages")

    with op.batch_alter_table("send_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_send_queue_actor"))

    # ### end Alembic commands ###
