"""increase field length

Revision ID: 7f163d621f13
Revises: 03258111eef1
Create Date: 2025-01-22 08:59:50.114846

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f163d621f13"
down_revision = "03258111eef1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_extra_field", schema=None) as batch_op:
        batch_op.alter_column(
            "label",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=1024),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_extra_field", schema=None) as batch_op:
        batch_op.alter_column(
            "label",
            existing_type=sa.String(length=1024),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
