"""Add post_url_type option for communities

Revision ID: 801a68148235
Revises: fa8677acf5ee
Create Date: 2025-11-11 03:28:12.175811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801a68148235'
down_revision = 'fa8677acf5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_url_type', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('post_url_type')

    # ### end Alembic commands ###
