"""notif subtypes

Revision ID: 809371c5b2ee
Revises: 755c3ffc142b
Create Date: 2025-05-02 10:18:35.616538

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "809371c5b2ee"
down_revision = "755c3ffc142b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtype", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("targets", sa.JSON(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_notification_notif_type"), ["notif_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_subtype"), ["subtype"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_subtype"))
        batch_op.drop_index(batch_op.f("ix_notification_notif_type"))
        batch_op.drop_column("targets")
        batch_op.drop_column("subtype")

    # ### end Alembic commands ###
