"""remove rules

Revision ID: 8afe3ee4fad0
Revises: 5ddd5f8fbbd1
Create Date: 2025-06-13 20:04:47.309537

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8afe3ee4fad0"
down_revision = "5ddd5f8fbbd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("rules_html")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rules_html", sa.TEXT(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
