"""joined column in conversation_member table

Revision ID: 8bfaa7ebb160
Revises: fb3a5a7696f7
Create Date: 2025-10-08 04:23:02.477316

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bfaa7ebb160"
down_revision = "fb3a5a7696f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_member", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "joined", sa.Boolean(), server_default=sa.sql.true(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_member", schema=None) as batch_op:
        batch_op.drop_column("joined")

    # ### end Alembic commands ###
