"""additional admin settings

Revision ID: 8e49c7efa647
Revises: 6531bb60f04a
Create Date: 2025-06-12 15:36:26.570513

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e49c7efa647"
down_revision = "6531bb60f04a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("enable_gif_reply_rep_decrease", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("enable_chan_image_filter", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("enable_this_comment_filter", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("enable_this_comment_filter")
        batch_op.drop_column("enable_chan_image_filter")
        batch_op.drop_column("enable_gif_reply_rep_decrease")

    # ### end Alembic commands ###
