"""override comment collapse

Revision ID: 8ed167b06fd7
Revises: e1c6576eaa4b
Create Date: 2026-07-25 14:26:05.338956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed167b06fd7'
down_revision = 'e1c6576eaa4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collapsible', sa.Boolean(), nullable=True, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.drop_column('collapsible')

    # ### end Alembic commands ###
