"""archived comments

Revision ID: 8f05d68118d0
Revises: e44dfb9a157f
Create Date: 2026-04-05 14:54:27.874601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f05d68118d0'
down_revision = 'e44dfb9a157f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_post_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('post_reply_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archived_post_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archived_post_reply_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archived_post_reply_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_post_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archived_post_reply_user_id'))
        batch_op.drop_index(batch_op.f('ix_archived_post_reply_post_id'))

    op.drop_table('archived_post_reply')
    # ### end Alembic commands ###
