"""contact email

Revision ID: 91a931afd6d9
Revises: 08b3f718df5d
Create Date: 2024-04-12 16:22:32.137053

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91a931afd6d9"
down_revision = "08b3f718df5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("contact_email", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("contact_email")

    # ### end Alembic commands ###
