"""user follow counts

Revision ID: 9208f044a1db
Revises: 1adb45ab3971
Create Date: 2026-06-19 23:07:40.351884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9208f044a1db'
down_revision = '1adb45ab3971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True, server_default=sa.sql.false()))
        batch_op.create_index(batch_op.f('ix_post_private'), ['private'], unique=False)

    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True, server_default=sa.sql.false()))
        batch_op.create_index(batch_op.f('ix_post_reply_private'), ['private'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_following', sa.Integer(), nullable=True, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('num_followers', sa.Integer(), nullable=True, server_default=sa.text('0')))

    with op.batch_alter_table('user_follow_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_follow_request_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follow_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follow_request_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('num_followers')
        batch_op.drop_column('num_following')

    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reply_private'))
        batch_op.drop_column('private')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_private'))
        batch_op.drop_column('private')

    # ### end Alembic commands ###
