"""additional js

Revision ID: 93bb3098ea31
Revises: 629e85034a4b
Create Date: 2025-06-26 14:17:56.286213

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93bb3098ea31"
down_revision = "629e85034a4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("additional_js", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("additional_js")

    # ### end Alembic commands ###
