"""site_default_filter

Revision ID: 9433fc1356f7
Revises: 07089cee1afb
Create Date: 2025-03-12 14:08:30.289407

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9433fc1356f7"
down_revision = "07089cee1afb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_filter", sa.String(length=20), nullable=True)
        )

    op.execute(sa.DDL("UPDATE \"site\" SET default_filter = 'popular'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("default_filter")

    # ### end Alembic commands ###
