"""community remote language

Revision ID: 94828ddc7c63
Revises: 5487a1886c62
Create Date: 2024-05-08 20:55:23.821386

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "94828ddc7c63"
down_revision = "5487a1886c62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ignore_remote_language", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("ignore_remote_language")

    # ### end Alembic commands ###
