"""add indexable property

Revision ID: 959c096c0211
Revises: 7524920417ef
Create Date: 2026-01-14 12:15:03.987106

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "959c096c0211"
down_revision = "7524920417ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_indexable"), ["indexable"], unique=False
        )

    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "indexable", sa.Boolean(), server_default=sa.sql.true(), nullable=True
            )
        )
        batch_op.create_index(
            batch_op.f("ix_post_reply_indexable"), ["indexable"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_reply_indexable"))
        batch_op.drop_column("indexable")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_indexable"))

    # ### end Alembic commands ###
