"""tag ban

Revision ID: 9752fb47d7a6
Revises: 20ee24728510
Create Date: 2024-05-12 12:46:09.954438

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9752fb47d7a6"
down_revision = "20ee24728510"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("banned", sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f("ix_tag_banned"), ["banned"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tag_banned"))
        batch_op.drop_column("banned")
        batch_op.drop_column("post_count")

    # ### end Alembic commands ###
