"""user follow pk

Revision ID: 97e954045fd6
Revises: 7752ded50189
Create Date: 2026-07-03 21:42:25.519081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e954045fd6'
down_revision = '7752ded50189'
branch_labels = None
depends_on = None


def upgrade():
    # The table currently has a composite primary key on
    # (local_user_id, remote_user_id). Drop it before we can add a new one and
    # before those columns can be made nullable.
    op.execute('ALTER TABLE user_follower DROP CONSTRAINT user_follower_pkey')

    # Add an autoincrementing SERIAL column: this backfills a unique value for
    # every existing row and serves as the new primary key in one step.
    op.execute('ALTER TABLE user_follower ADD COLUMN id SERIAL PRIMARY KEY')

    with op.batch_alter_table('user_follower', schema=None) as batch_op:
        batch_op.alter_column('local_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('remote_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_follower_is_inward'), ['is_inward'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follower_local_user_id'), ['local_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follower_remote_user_id'), ['remote_user_id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follower', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follower_remote_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_follower_local_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_follower_is_inward'))
        batch_op.alter_column('remote_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('local_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        # Dropping the column also drops the id primary key and its sequence.
        batch_op.drop_column('id')

    # Restore the original composite primary key.
    op.execute('ALTER TABLE user_follower ADD PRIMARY KEY (local_user_id, remote_user_id)')

    # ### end Alembic commands ###
