"""event location

Revision ID: 9feef6cf2e9f
Revises: d06f9447eb2f
Create Date: 2025-08-11 19:57:08.989252

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9feef6cf2e9f"
down_revision = "d06f9447eb2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("location")

    # ### end Alembic commands ###
