"""post timezone

Revision ID: a14e9b58e00b
Revises: abdb0f420a57
Create Date: 2025-07-05 20:40:34.333087

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a14e9b58e00b"
down_revision = "abdb0f420a57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timezone", sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("timezone")

    # ### end Alembic commands ###
