"""feedmember banned

Revision ID: a1e76faf23e6
Revises: 63c587b2c6bc
Create Date: 2025-02-25 09:33:46.945563

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1e76faf23e6"
down_revision = "63c587b2c6bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feed_is_instance_feed"), ["is_instance_feed"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_feed_public"), ["public"], unique=False)
        batch_op.create_index(batch_op.f("ix_feed_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("feed_member", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_banned", sa.Boolean(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_feed_member_is_banned"), ["is_banned"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_member_is_banned"))
        batch_op.drop_column("is_banned")

    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_user_id"))
        batch_op.drop_index(batch_op.f("ix_feed_public"))
        batch_op.drop_index(batch_op.f("ix_feed_is_instance_feed"))

    # ### end Alembic commands ###
