"""remove avg comment length

Revision ID: a32b474a40dd
Revises: e76f2067e689
Create Date: 2024-05-23 15:24:12.575063

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a32b474a40dd"
down_revision = "e76f2067e689"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("average_comment_length")
        batch_op.drop_column("comment_length_warning")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "comment_length_warning",
                sa.INTEGER(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "average_comment_length",
                sa.INTEGER(),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
