"""community archive optout

Revision ID: a4d010278fee
Revises: 7928b07490fe
Create Date: 2025-07-30 15:20:52.071525

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a4d010278fee"
down_revision = "7928b07490fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "can_be_archived",
                sa.Boolean(),
                nullable=True,
                server_default=sa.text("true"),
            )
        )
        batch_op.create_index(
            batch_op.f("ix_community_can_be_archived"),
            ["can_be_archived"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_community_can_be_archived"))
        batch_op.drop_column("can_be_archived")

    # ### end Alembic commands ###
