"""topic: show_posts_in_children

Revision ID: a4debcf5ac6f
Revises: e23ce3d53def
Create Date: 2024-11-08 14:46:56.009352

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4debcf5ac6f"
down_revision = "e23ce3d53def"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("show_posts_in_children", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.drop_column("show_posts_in_children")

    # ### end Alembic commands ###
