"""add privacy_url to site

Revision ID: a7b9f2c8e1d4
Revises: c7871b37747f
Create Date: 2025-09-11 15:35:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7b9f2c8e1d4"
down_revision = "c7871b37747f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("privacy_url", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("privacy_url")

    # ### end Alembic commands ###
