"""Adding remote community may be blocked for default user.

Revision ID: aad270b3e669
Revises: 461c871f0f58
Create Date: 2025-10-25 09:16:22.865878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad270b3e669'
down_revision = '461c871f0f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_default_user_add_remote_community', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('allow_default_user_add_remote_community')

    # ### end Alembic commands ###
