"""community rss url

Revision ID: abdb0f420a57
Revises: 05e8bbb98977
Create Date: 2025-07-04 20:43:19.163119

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abdb0f420a57"
down_revision = "05e8bbb98977"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rss_url", sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column("private", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("private")
        batch_op.drop_column("rss_url")

    # ### end Alembic commands ###
