"""mastodon oauth

Revision ID: afcf39297eec
Revises: f382f01ea8be
Create Date: 2025-06-29 17:20:42.395041

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "afcf39297eec"
down_revision = "f382f01ea8be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("mastodon_oauth_id", sa.String(length=64), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_mastodon_oauth_id"), ["mastodon_oauth_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_mastodon_oauth_id"))
        batch_op.drop_column("mastodon_oauth_id")

    # ### end Alembic commands ###
