"""password_updated_at to user

Revision ID: b15d2a8704cc
Revises: a14e9b58e00b
Create Date: 2025-07-05 09:36:59.512600

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b15d2a8704cc"
down_revision = "a14e9b58e00b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_updated_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password_updated_at")

    # ### end Alembic commands ###
