"""user read languages

Revision ID: b1aae4ad16d8
Revises: d624c7d45955
Create Date: 2025-03-22 05:22:41.163934

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1aae4ad16d8"
down_revision = "d624c7d45955"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "read_language_ids", postgresql.ARRAY(sa.Integer()), nullable=True
            )
        )

    conn = op.get_bind()

    # Retrieve the ID of the English language
    set_to = conn.execute(
        sa.text('SELECT id FROM "language" WHERE code = :code'), {"code": "en"}
    ).scalar()

    if set_to is not None:
        conn.execute(
            sa.text(
                'UPDATE "post" SET language_id = :set_to WHERE language_id IS NULL'
            ),
            {"set_to": set_to},
        )
        conn.execute(
            sa.text(
                'UPDATE "post_reply" SET language_id = :set_to WHERE language_id IS NULL'
            ),
            {"set_to": set_to},
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("read_language_ids")

    # ### end Alembic commands ###
