"""date of first federation column on communities table

Revision ID: b1dd589ac3f9
Revises: 12664244e54d
Create Date: 2025-12-21 04:37:25.117261

"""

from alembic import op
import sqlalchemy as sa

from datetime import datetime
from zoneinfo import ZoneInfo


# revision identifiers, used by Alembic.
revision = "b1dd589ac3f9"
down_revision = "12664244e54d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "first_federated_at",
                sa.DateTime(),
                server_default=sa.func.now(),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_community_first_federated_at"),
            ["first_federated_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_community_first_federated_at"))
        batch_op.drop_column("first_federated_at")

    # ### end Alembic commands ###
