"""post_reply indexes for search

Revision ID: b2661139d87c
Revises: 52380f7885d1
Create Date: 2025-04-04 18:09:11.361415

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2661139d87c"
down_revision = "52380f7885d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_reply_from_bot"), ["from_bot"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_post_reply_nsfl"), ["nsfl"], unique=False)
        batch_op.create_index(batch_op.f("ix_post_reply_nsfw"), ["nsfw"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_reply_nsfw"))
        batch_op.drop_index(batch_op.f("ix_post_reply_nsfl"))
        batch_op.drop_index(batch_op.f("ix_post_reply_from_bot"))

    # ### end Alembic commands ###
