"""image hash

Revision ID: b6169d302035
Revises: 2c3a0e0c5b57
Create Date: 2025-04-19 17:35:55.015204

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6169d302035"
down_revision = "2c3a0e0c5b57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hash", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_file_hash"), ["hash"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_hash"))
        batch_op.drop_column("hash")

    # ### end Alembic commands ###
