"""rss token

Revision ID: b9846545ef49
Revises: 1521210bd33a
Create Date: 2026-06-27 13:26:18.467453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9846545ef49'
down_revision = '1521210bd33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_token', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_rss_token'), ['rss_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_rss_token'))
        batch_op.drop_column('rss_token')

    # ### end Alembic commands ###
