"""community join guids

Revision ID: ba02110b0962
Revises: eb61453d6782
Create Date: 2025-06-09 19:57:19.691929

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba02110b0962"
down_revision = "eb61453d6782"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community_join_request", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_community_join_request_uuid"), ["uuid"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community_join_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_community_join_request_uuid"))
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
