"""community keyword filter

Revision ID: ba02c97c1722
Revises: 5a19900198e9
Create Date: 2025-07-08 14:59:05.441051

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba02c97c1722"
down_revision = "5a19900198e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("community_keyword_filter", sa.String(length=150), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_user_bot"), ["bot"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_bot_override"), ["bot_override"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_bot_override"))
        batch_op.drop_index(batch_op.f("ix_user_bot"))
        batch_op.drop_column("community_keyword_filter")

    # ### end Alembic commands ###
