"""post_reply api

Revision ID: bb2b422094cc
Revises: b1aae4ad16d8
Create Date: 2025-03-23 15:51:18.929007

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb2b422094cc"
down_revision = "b1aae4ad16d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("path", postgresql.ARRAY(sa.Integer()), nullable=True)
        )
        batch_op.add_column(sa.Column("child_count", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_post_reply_path"), ["path"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_post_reply_root_id"), ["root_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_reply_root_id"))
        batch_op.drop_index(batch_op.f("ix_post_reply_path"))
        batch_op.drop_column("child_count")
        batch_op.drop_column("path")

    # ### end Alembic commands ###
