"""Add cron job logs to db

Revision ID: bf436ec2a94b
Revises: 8f05d68118d0
Create Date: 2026-04-06 02:24:59.950389

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf436ec2a94b"
down_revision = "8f05d68118d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cron_job_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.Column("frequency", sa.Interval(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cron_job_log")
    # ### end Alembic commands ###
