"""comment sticky and replies enabled

Revision ID: bfb5ff64a9d5
Revises: eaf7845f39f1
Create Date: 2025-07-15 15:04:20.942895

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "bfb5ff64a9d5"
down_revision = "eaf7845f39f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "replies_enabled",
                sa.Boolean(),
                nullable=False,
                default=True,
                server_default=sa.text("true"),
            )
        )
        batch_op.add_column(sa.Column("sticky", sa.Boolean(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_post_reply_sticky"), ["sticky"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_reply_sticky"))
        batch_op.drop_column("sticky")
        batch_op.drop_column("replies_enabled")

    # ### end Alembic commands ###
