"""post sticky

Revision ID: c061eec8c280
Revises: 7ec262d6a3de
Create Date: 2025-04-18 20:46:15.519064

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c061eec8c280"
down_revision = "7ec262d6a3de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_sticky"), ["sticky"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_sticky"))

    # ### end Alembic commands ###
