"""send queue

Revision ID: c28b33d0bf0c
Revises: abf29fd7b4c4
Create Date: 2025-04-09 20:18:22.916367

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c28b33d0bf0c"
down_revision = "abf29fd7b4c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "send_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("destination_domain", sa.String(length=255), nullable=True),
        sa.Column("destination", sa.String(length=1024), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("private_key", sa.String(length=2000), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("retry_reason", sa.String(length=255), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("send_after", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("send_queue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_send_queue_destination_domain"),
            ["destination_domain"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_send_queue_send_after"), ["send_after"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("send_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_send_queue_send_after"))
        batch_op.drop_index(batch_op.f("ix_send_queue_destination_domain"))

    op.drop_table("send_queue")
    # ### end Alembic commands ###
