"""can send pms

Revision ID: c4f4625a6922
Revises: 5eb2bf95ed8b
Create Date: 2026-06-24 13:32:14.750131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f4625a6922'
down_revision = '5eb2bf95ed8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_send_pm', sa.Boolean(), nullable=True, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_send_pm')

    # ### end Alembic commands ###
