"""add markdown site fields

Revision ID: c579fa943828
Revises: deae43a990ff
Create Date: 2025-07-24 11:21:52.860482

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c579fa943828"
down_revision = "deae43a990ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sidebar", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("legal_information", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("about", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("about")
        batch_op.drop_column("legal_information")
        batch_op.drop_column("sidebar")

    # ### end Alembic commands ###
