"""adding FeedJoinRequest

Revision ID: c6f8be3b5dcb
Revises: ca02c3553850
Create Date: 2025-02-10 17:09:00.236344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f8be3b5dcb'
down_revision = 'ca02c3553850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_join_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_join_request_feed_id'), ['feed_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_join_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_join_request_feed_id'))

    op.drop_table('feed_join_request')
    # ### end Alembic commands ###
