"""gallery migration

Revision ID: c732bc66a5b8
Revises: 461c871f0f58
Create Date: 2025-11-02 14:39:01.271949

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c732bc66a5b8"
down_revision = "461c871f0f58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_file",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "file_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_file")
    # ### end Alembic commands ###
