"""reminders

Revision ID: c7871b37747f
Revises: 02f2fc3f19f1
Create Date: 2025-09-10 17:04:09.609687

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7871b37747f"
down_revision = "02f2fc3f19f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("remind_at", sa.DateTime(), nullable=True),
        sa.Column("reminder_type", sa.Integer(), nullable=True),
        sa.Column("reminder_destination", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reminder_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminder_user_id"))

    op.drop_table("reminder")
    # ### end Alembic commands ###
