"""post boost

Revision ID: c831b9c7eee9
Revises: 97e954045fd6
Create Date: 2026-07-06 19:27:34.620340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c831b9c7eee9'
down_revision = '97e954045fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_boost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_boost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_boost_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_boost_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_boost_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_boosts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_boosts')

    with op.batch_alter_table('post_boost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_boost_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_boost_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_boost_created_at'))

    op.drop_table('post_boost')
    # ### end Alembic commands ###
