"""comm_member composite idx

Revision ID: c86d6e395aea
Revises: c7871b37747f
Create Date: 2025-09-12 11:02:41.123237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86d6e395aea'
down_revision = 'c7871b37747f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_member', schema=None) as batch_op:
        batch_op.create_index('ix_community_member_community_banned', ['community_id', 'is_banned'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_member', schema=None) as batch_op:
        batch_op.drop_index('ix_community_member_community_banned')

    # ### end Alembic commands ###
