"""adding instance_feed column to feed

Revision ID: ca02c3553850
Revises: b2df3ae9bf38
Create Date: 2025-02-06 14:32:16.441230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca02c3553850'
down_revision = 'b2df3ae9bf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_instance_feed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('is_instance_feed')

    # ### end Alembic commands ###
