"""additional event fields

Revision ID: d06f9447eb2f
Revises: 569d6f8c32bd
Create Date: 2025-08-11 19:56:33.646658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06f9447eb2f'
down_revision = '569d6f8c32bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('participant_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('join_mode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('external_participation_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('anonymous_participation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('event_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participation_message', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_user', schema=None) as batch_op:
        batch_op.drop_column('participation_message')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('online')
        batch_op.drop_column('anonymous_participation')
        batch_op.drop_column('external_participation_url')
        batch_op.drop_column('join_mode')
        batch_op.drop_column('participant_count')
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
