"""index on vote.author_id

Revision ID: d32ef1893ce4
Revises: 26138ecda7c3
Create Date: 2024-11-15 16:40:21.080337

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d32ef1893ce4"
down_revision = "26138ecda7c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply_vote", schema=None) as batch_op:
        try:
            batch_op.create_index(
                batch_op.f("ix_post_reply_vote_author_id"), ["author_id"], unique=False
            )
        except:
            ...

    with op.batch_alter_table("post_vote", schema=None) as batch_op:
        try:
            batch_op.create_index(
                batch_op.f("ix_post_vote_author_id"), ["author_id"], unique=False
            )
        except:
            ...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_vote", schema=None) as batch_op:
        try:
            batch_op.drop_index(batch_op.f("ix_post_vote_author_id"))
        except:
            ...

    with op.batch_alter_table("post_reply_vote", schema=None) as batch_op:
        try:
            batch_op.drop_index(batch_op.f("ix_post_reply_vote_author_id"))
        except:
            ...

    # ### end Alembic commands ###
