"""reposters

Revision ID: d4e8677025cd
Revises: 7b8bf43fa079
Create Date: 2026-09-26 10:37:09.454960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'd4e8677025cd'
down_revision = '7b8bf43fa079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_reposter', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_from_reposter'), ['from_reposter'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reposter', sa.Boolean(), server_default=sa.sql.false(), nullable=True))
        batch_op.add_column(sa.Column('reposter_override', sa.Boolean(), server_default=sa.sql.false(), nullable=True))
        batch_op.add_column(sa.Column('ignore_reposters', sa.Integer(), server_default=sa.text('0'), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_reposter'), ['reposter'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reposter_override'), ['reposter_override'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reposter_override'))
        batch_op.drop_index(batch_op.f('ix_user_reposter'))
        batch_op.drop_column('ignore_reposters')
        batch_op.drop_column('reposter_override')
        batch_op.drop_column('reposter')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_from_reposter'))
        batch_op.drop_column('from_reposter')

    # ### end Alembic commands ###
