"""post ranking scaled

Revision ID: d624c7d45955
Revises: 9433fc1356f7
Create Date: 2025-03-18 20:23:12.359150

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d624c7d45955"
down_revision = "9433fc1356f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ranking_scaled", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_post_ranking_scaled"), ["ranking_scaled"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_ranking_scaled"))
        batch_op.drop_column("ranking_scaled")

    # ### end Alembic commands ###
