"""add CommunityThemeAllowed model

Revision ID: d8d1540cd4d6
Revises: 8f05d68118d0
Create Date: 2026-04-08 09:45:21.383907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d1540cd4d6'
down_revision = '8f05d68118d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_theme_allowed',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('community_id', 'user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_theme_allowed')
    # ### end Alembic commands ###
