"""Add column for instance-wide sticky posts

Revision ID: dd04745585ac
Revises: 959c096c0211
Create Date: 2026-01-16 02:43:28.261035

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd04745585ac"
down_revision = "959c096c0211"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "instance_sticky",
                sa.Boolean(),
                server_default=sa.sql.false(),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_post_instance_sticky"), ["instance_sticky"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_instance_sticky"))
        batch_op.drop_column("instance_sticky")

    # ### end Alembic commands ###
