"""rename site fields for html

Revision ID: deae43a990ff
Revises: 0e4d615995a3
Create Date: 2025-07-24 11:20:38.182770

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "deae43a990ff"
down_revision = "0e4d615995a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sidebar_html", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("legal_information_html", sa.Text(), nullable=True)
        )
        batch_op.add_column(sa.Column("about_html", sa.Text(), nullable=True))
        batch_op.drop_column("legal_information")
        batch_op.drop_column("about")
        batch_op.drop_column("sidebar")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sidebar", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("about", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "legal_information", sa.TEXT(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("about_html")
        batch_op.drop_column("legal_information_html")
        batch_op.drop_column("sidebar_html")

    # ### end Alembic commands ###
