"""instance nodeinfo href

Revision ID: dfba54bdaeb2
Revises: a32b474a40dd
Create Date: 2024-05-23 14:14:11.293845

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dfba54bdaeb2"
down_revision = "a32b474a40dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("nodeinfo_href", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.drop_column("nodeinfo_href")

    # ### end Alembic commands ###
