"""community translation

Revision ID: e0def05558bc
Revises: b38b253309dd
Create Date: 2025-11-07 14:10:27.416985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0def05558bc'
down_revision = 'b38b253309dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('always_translate', sa.Boolean(), nullable=True))

    with op.batch_alter_table('post_reply_vote', schema=None) as batch_op:
        batch_op.drop_constraint('post_reply_vote_post_reply_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post_reply', ['post_reply_id'], ['id'])

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.drop_constraint('post_vote_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_vote_post_id_fkey', 'post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_reply_vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_reply_vote_post_reply_id_fkey', 'post_reply', ['post_reply_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('always_translate')

    # ### end Alembic commands ###
