"""community translation

Revision ID: e0def05558bc
Revises: b38b253309dd
Create Date: 2025-11-07 14:10:27.416985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0def05558bc'
down_revision = 'b38b253309dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('always_translate', sa.Boolean(), nullable=True))

    # Removed auto-generated constraint changes that were removing ON DELETE CASCADE
    # These constraints should not be modified by this migration

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('always_translate')

    # ### end Alembic commands ###
