"""block community flair

Revision ID: e1c6576eaa4b
Revises: 544946659eb7
Create Date: 2026-07-14 22:14:43.675845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c6576eaa4b'
down_revision = '544946659eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_flair_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('community_flair_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_flair_id'], ['community_flair.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_flair_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_flair_block_community_flair_id'), ['community_flair_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_flair_block_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_flair_block_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_flair_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_flair_block_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_flair_block_community_id'))
        batch_op.drop_index(batch_op.f('ix_community_flair_block_community_flair_id'))

    op.drop_table('community_flair_block')
    # ### end Alembic commands ###
