"""post list indexes

Revision ID: e4935b360d97
Revises: 8457362452d9
Create Date: 2026-04-10 11:10:18.114312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4935b360d97'
down_revision = '8457362452d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_feed_active', [sa.literal_column('last_active DESC')], unique=False, postgresql_where=sa.text('deleted = false AND status > 0 AND last_active IS NOT NULL'))
        batch_op.create_index('ix_post_feed_community', ['community_id', sa.literal_column('sticky DESC'), sa.literal_column('posted_at DESC')], unique=False, postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.create_index('ix_post_feed_hot', [sa.literal_column('instance_sticky DESC'), sa.literal_column('ranking DESC'), sa.literal_column('posted_at DESC')], unique=False, postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.create_index('ix_post_feed_new', [sa.literal_column('instance_sticky DESC'), sa.literal_column('posted_at DESC')], unique=False, postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.create_index('ix_post_feed_scaled', [sa.literal_column('instance_sticky DESC'), sa.literal_column('ranking_scaled DESC'), sa.literal_column('ranking DESC'), sa.literal_column('posted_at DESC')], unique=False, postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.create_index('ix_post_feed_top', [sa.literal_column('posted_at DESC'), sa.literal_column('score DESC')], unique=False, postgresql_where=sa.text('deleted = false AND status > 0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_feed_top', postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.drop_index('ix_post_feed_scaled', postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.drop_index('ix_post_feed_new', postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.drop_index('ix_post_feed_hot', postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.drop_index('ix_post_feed_community', postgresql_where=sa.text('deleted = false AND status > 0'))
        batch_op.drop_index('ix_post_feed_active', postgresql_where=sa.text('deleted = false AND status > 0 AND last_active IS NOT NULL'))

    # ### end Alembic commands ###
