"""ap_id on chatmessage

Revision ID: e9062ab3305e
Revises: a1e76faf23e6
Create Date: 2025-02-27 20:38:12.001221

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9062ab3305e"
down_revision = "a1e76faf23e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ap_id", sa.String(length=255), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_chat_message_ap_id"), ["ap_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_message_ap_id"))
        batch_op.drop_column("ap_id")

    # ### end Alembic commands ###
