"""comm posting warning

Revision ID: e94c00548fff
Revises: 77af2bc5bc3b
Create Date: 2026-10-06 11:23:34.602826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94c00548fff'
down_revision = '77af2bc5bc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posting_warning_override', sa.String(length=512), server_default=sa.text("''"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('posting_warning_override')

    # ### end Alembic commands ###
