"""user additional css

Revision ID: eb61453d6782
Revises: eceb4d977aed
Create Date: 2025-06-07 07:08:46.517384

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb61453d6782"
down_revision = "eceb4d977aed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("additional_css", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("additional_css")

    # ### end Alembic commands ###
