"""user timezone longer

Revision ID: eceb4d977aed
Revises: 59792d8577df
Create Date: 2025-06-07 06:18:55.289296

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eceb4d977aed"
down_revision = "59792d8577df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "timezone",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=30),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "timezone",
            existing_type=sa.String(length=30),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
