"""flair ap_id

Revision ID: f153c932397d
Revises: 086ebbe4f31b
Create Date: 2025-08-29 21:25:13.708324

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f153c932397d"
down_revision = "086ebbe4f31b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community_flair", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ap_id", sa.String(length=255), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_community_flair_ap_id"), ["ap_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community_flair", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_community_flair_ap_id"))
        batch_op.drop_column("ap_id")

    # ### end Alembic commands ###
