"""default filter

Revision ID: f1f38dabd541
Revises: f6d6bd92cf88
Create Date: 2024-08-16 13:37:02.854345

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1f38dabd541"
down_revision = "f6d6bd92cf88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_filter", sa.String(length=25), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("default_filter")

    # ### end Alembic commands ###
