"""remove home checkbox

Revision ID: f2fa25ab5e52
Revises: 98680738ebb0
Create Date: 2024-12-05 13:46:20.291051

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2fa25ab5e52"
down_revision = "98680738ebb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_column("show_home")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("show_home", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
