"""show_subscribed_communities

Revision ID: f382f01ea8be
Revises: 93bb3098ea31
Create Date: 2025-06-27 14:55:32.724747

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f382f01ea8be"
down_revision = "93bb3098ea31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("show_subscribed_communities", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("show_subscribed_communities")

    # ### end Alembic commands ###
