"""discord oauth

Revision ID: add_discord_oauth_id
Revises: f382f01ea8be
Create Date: 2023-11-15 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f392f91ea9be"
down_revision = "afcf39297eec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("discord_oauth_id", sa.String(length=64), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_discord_oauth_id"), ["discord_oauth_id"], unique=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_discord_oauth_id"))
        batch_op.drop_column("discord_oauth_id")
    # ### end Alembic commands ###
