"""post_reply_path gin index

Revision ID: f5e09ad62de3
Revises: 2ea29b01e5c6
Create Date: 2025-04-23 20:12:55.217512

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5e09ad62de3"
down_revision = "2ea29b01e5c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.create_index(
            "idx_post_reply_path", ["path"], unique=False, postgresql_using="gin"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_reply", schema=None) as batch_op:
        batch_op.drop_index("idx_post_reply_path", postgresql_using="gin")

    # ### end Alembic commands ###
