"""adding notif_type to notifications

Revision ID: f668bbb1160f
Revises: c28b33d0bf0c
Create Date: 2025-04-10 18:49:36.904790

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f668bbb1160f"
down_revision = "c28b33d0bf0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notif_type", sa.Integer(), nullable=True))

    # setting the NOTIF_DEFAULT on all rows to not break existing code
    # while transitioning to new notifications
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.execute('UPDATE "notification" SET notif_type = 999')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_column("notif_type")

    # ### end Alembic commands ###
