"""adding columns to feedmember

Revision ID: f739ae20c800
Revises: c6f8be3b5dcb
Create Date: 2025-02-12 13:13:12.269194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f739ae20c800'
down_revision = 'c6f8be3b5dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_new_communities', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_member', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('notify_new_communities')
        batch_op.drop_column('is_owner')

    # ### end Alembic commands ###
