"""batched activities

Revision ID: f80b8607e38f
Revises: b15d2a8704cc
Create Date: 2025-07-06 16:26:05.858546

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f80b8607e38f"
down_revision = "b15d2a8704cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("community_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_batch", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_batch_community_id"), ["community_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_batch_instance_id"), ["instance_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_batch_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_batch_source_type"), ["source_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_batch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_batch_source_type"))
        batch_op.drop_index(batch_op.f("ix_activity_batch_source_id"))
        batch_op.drop_index(batch_op.f("ix_activity_batch_instance_id"))
        batch_op.drop_index(batch_op.f("ix_activity_batch_community_id"))

    op.drop_table("activity_batch")
    # ### end Alembic commands ###
