"""Add allow_community_themes setting to user database

Revision ID: fa312daf8d0a
Revises: 88e7c7037417
Create Date: 2026-03-29 08:59:10.433258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa312daf8d0a'
down_revision = '88e7c7037417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_community_themes', sa.Boolean(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('allow_community_themes')

    # ### end Alembic commands ###
