"""post reply count index

Revision ID: fa8677acf5ee
Revises: e0def05558bc
Create Date: 2025-11-08 13:01:14.790359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8677acf5ee'
down_revision = 'e0def05558bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reply_count'), ['reply_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reply_count'))

    # ### end Alembic commands ###
