"""instance silencing

Revision ID: fbcb15c817e0
Revises: ccad5f15096c
Create Date: 2026-05-08 14:45:51.068332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcb15c817e0'
down_revision = 'ccad5f15096c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('silenced', sa.Boolean(), server_default=sa.sql.false(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instance_silenced'), ['silenced'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_silenced'))
        batch_op.drop_column('silenced')

    # ### end Alembic commands ###
