"""emoji reactions

Revision ID: fbd19ecc0c3a
Revises: 2dab0fc0b964
Create Date: 2025-12-12 15:09:44.682900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd19ecc0c3a'
down_revision = '2dab0fc0b964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('aliases', sa.String(length=100), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emoji', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emoji_aliases'), ['aliases'], unique=False)
        batch_op.create_index(batch_op.f('ix_emoji_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emoji_token'), ['token'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji_reactions', sa.JSON(), nullable=True))

    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji_reactions', sa.JSON(), nullable=True))

    with op.batch_alter_table('post_reply_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji', sa.String(length=20), nullable=True))

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.drop_column('emoji')

    with op.batch_alter_table('post_reply_vote', schema=None) as batch_op:
        batch_op.drop_column('emoji')

    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.drop_column('emoji_reactions')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('emoji_reactions')

    with op.batch_alter_table('emoji', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emoji_token'))
        batch_op.drop_index(batch_op.f('ix_emoji_instance_id'))
        batch_op.drop_index(batch_op.f('ix_emoji_aliases'))

    op.drop_table('emoji')
    # ### end Alembic commands ###
