"""hide low quality

Revision ID: fc3b6ff48330
Revises: 0c3712a11363
Create Date: 2025-05-21 12:11:34.147756

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc3b6ff48330"
down_revision = "0c3712a11363"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hide_low_quality", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("hide_low_quality")

    # ### end Alembic commands ###
