#!/bin/bash
# Quick start script for PeachPie development/testing

set -e

echo "PeachPie Quick Start"
echo "===================="
echo ""

# Check for required tools
command -v docker >/dev/null 2>&1 || { echo "Error: docker is required but not installed." >&2; exit 1; }
command -v docker-compose >/dev/null 2>&1 || { echo "Error: docker-compose is required but not installed." >&2; exit 1; }

# Set defaults if not provided
export SERVER_NAME=${SERVER_NAME:-"localhost:5000"}
export SECRET_KEY=${SECRET_KEY:-$(openssl rand -hex 32)}
export ADMIN_USERNAME=${ADMIN_USERNAME:-"admin"}
export ADMIN_EMAIL=${ADMIN_EMAIL:-"admin@localhost"}
export ADMIN_PASSWORD=${ADMIN_PASSWORD:-$(openssl rand -base64 12)}
export FLASK_ENV=${FLASK_ENV:-"development"}
export FLASK_DEBUG=${FLASK_DEBUG:-"1"}

# Create .env file
cat > .env.dev <<EOF
# Generated by quickstart.sh
SERVER_NAME=${SERVER_NAME}
SECRET_KEY=${SECRET_KEY}
DATABASE_URL=postgresql://peachpie:peachpie@localhost:5432/peachpie
REDIS_URL=redis://localhost:6379/0
FLASK_ENV=${FLASK_ENV}
FLASK_DEBUG=${FLASK_DEBUG}

# Admin credentials
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Federation
FEDERATION_DOMAIN=${SERVER_NAME}
REQUIRE_SIGNATURES=false

# Development settings
ENABLE_DEBUG_ENDPOINTS=true
EXTRA_AP_LOGGING=1
EOF

echo "Starting PostgreSQL and Redis..."
docker-compose -f docker-compose.dev.yml up -d db redis

echo "Waiting for services to be ready..."
sleep 5

echo "Initializing database..."
export $(cat .env.dev | xargs)
python scripts/init_db.py --non-interactive

echo ""
echo "================================"
echo "PeachPie Test Instance Ready!"
echo "================================"
echo ""
echo "Admin credentials:"
echo "  Username: ${ADMIN_USERNAME}"
echo "  Email: ${ADMIN_EMAIL}"
echo "  Password: ${ADMIN_PASSWORD}"
echo ""
echo "Start the application with:"
echo "  flask run"
echo ""
echo "Start the federation worker with:"
echo "  python -m app.federation.processor"
echo ""
echo "Access the instance at:"
echo "  http://${SERVER_NAME}"
echo ""
echo "Environment saved to: .env.dev"
echo ""